### ISSUE TITLE
Leaderboard: Top Earners

### ISSUE THREAD

**Issue by rymksotnini** [unicef/bounties#10]
Descending list of users by the amount of bounties they've earned

Display Top 25, lazy load button at bottom of list to load/append next page

**Comment by tenthirtyone** [comment]
**Requirements**
1. Mobile/Desktop views
2. Make the required changes to display the submission leaderboard
6. Add your component to the `src/components/Leaderboard/index.jsx` file
7. Match the styles found at https://explorer.bounties.network/leaderboard and https://github.com/Bounties-Network/Explorer 

Example:
![image](https://user-images.githubusercontent.com/6285466/113196251-44c8df80-9231-11eb-8f7d-2012aa84f532.png)
