### ISSUE TITLE
Leaderboard: Top Issuers

### ISSUE THREAD

**Issue by rymksotnini** [unicef/bounties#11]
Descending list of users by the amount of bounties they've earned

Display Top 25, lazy load button at bottom of list to load/append next page

**Comment by tenthirtyone** [comment]
Requires #10 

**Requirements**
1. Mobile/Desktop views
2. Make the required changes to display the issuers leaderboard
6. Add your component to the `src/components/Leaderboard/index.jsx` file
7. Match the styles found at https://explorer.bounties.network/leaderboard and https://github.com/Bounties-Network/Explorer 

Example:
![image](https://user-images.githubusercontent.com/6285466/113196390-72ae2400-9231-11eb-9683-a51e3d2cb085.png)

**Comment by DivyanshiSingh** [comment]
Hey, @tenthirtyone I can start with this particular issue as soon as you can tell me about the data for bounty collection.

**Comment by DivyanshiSingh** [comment]
Do I need to keep the switch component the same as given in the design @tenthirtyone
